main: me.recar.addon.askyblock.LeaderBoardPlaceholdersPlugin
name: ASkyblock_LB_Placeholders
authors:
  - Recarnation
version: 1.1.0
depend:
  - ASkyBlock
  - PlaceholderAPI
commands:
  leaderboards:
    usage: <command>
    description: To See all Island Levels
    permission: aslb.top
  aslb-reload:
    usage: <command>
    description: Reload The Plugin
    permission: aslb.reload